# -*- coding: utf-8 -*-
"""jeonsae_ratio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CMLKyZtcnm4-dwQzRKHInhoOxJxwj5NJ
"""

# jeonse_ratio.py

def calc_jeonse_ratio(deposit, hedonic_price):
    """
    deposit: 전세금 (만원)
    hedonic_price: 적정 매매가 v0 (만원)
    """
    if hedonic_price is None or hedonic_price <= 0:
        return None

    ratio = deposit / hedonic_price
    return round(ratio, 3)